service: serverless-cd-demo-a1c8

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack

# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true
  stage: ${opt:stage, self:provider.stage}
  production:
    MESSAGE: 'I am prod'
  dev:
    MESSAGE: 'I am dev'

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  environment: ${self:custom.${self:custom.stage}}

functions:
  hello:
    handler: handler.main
    events:
      - http:
          path: /
          method: get

